# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01caaaef796d1be3fd17a19bb2ce06e1373f036185ff0ff55294558970bb6746e1a0d067e1eb86bab96f6bbae42a29e3ac9184472b29c424e597e5c3f3ccbc3d

test:
  secret_key_base: 7497872e73c5bc236f453509f7344116be1910ea4fe17a6c3ef50693b343155d8c4a0413da535c589dd0ebf225bc3ad4d0acdea774895457c3f16639ca15291d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
